### ISSUE TITLE
[ENHANCEMENT] add punctuation char to table and pop up a selection

### ISSUE THREAD

**Issue by igor-kobzev** [mike-fabian/ibus-table#121]
**Is your feature request related to a problem? Please describe.**
As Cangjie is used both in Hong Kong and Taiwan, I think it should natively support (that is, without turning to 重) all the punctuation marks that are in use. Unfortunately, there is no way to input single-quote mark (〈〉) in ibus-cangjie. Shouldn't this be included? 

**Describe the solution you'd like**
For example, in macOS and Windows you can input that by typing > and then choosing the right symbol in the selection popup. Ibus-table should allow this, too.

I think the following way suggested by Mike Fabian here https://github.com/kaio/ibus-table/issues/73, is the way to go (it's the same as used in Windows and macOS):

    1) add punctuation char to table and pop up a selection:

    I think if you want that < pops up a selection, then it should be added to VALID_INPUT_CHARS and the appropriate selection options should be added to the table and then the user chooses and commits as is normal for that table.

    You can already try that out right now. I don’t need to implement anything for this in ibus-table, this already works, it is just necessary to change the cangjie5 table.

    If you want to try that, download the source of the cangjie5.txt table you are using from here:

    https://github.com/definite/ibus-table-chinese/blob/master/tables/cangjie/cangjie5.txt

    open it in a text editor, add the lines

    >	〉	951
    >>	》	950
    <	〈	951
    <<	《	950

    at the end of the table (just before the END_TABLE line). Note that the white space separating the 3 columns must be a TAB!

    Then compile the table by executing

    $ /usr/bin/ibus-table-createdb -s cangjie5.txt

    which will create a cangjie5.db database file from the cangjie5.txt source file.

    Copy the new database file to the place where the old cangjie5.db is, i.e. to this place:

    sudo cp cangjie5.db /usr/share/ibus-table/tables/cangjie5.db

    If not using Gnome restart ibus:

    ibus restart

    If using Gnome log out of the desktop and log in again to restart ibus.

    Now you can try whether you like the changed behaviour of typing >, <, >>, and <<.

**Comment by mike-fabian** [comment]
If you use Fedora, it would be nice if you can test the 1.8.10 packages here:
https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/builds/

**Comment by igor-kobzev** [comment]
My old Surface that has Fedora is away so I will be able to test it next weekend. Maybe that's a little late, but I'll do it anyways!

**Comment by mike-fabian** [comment]
https://github.com/mike-fabian/ibus-table-chinese/releases/tag/1.8.10
