### ISSUE TITLE
status icon with input mode

### ISSUE THREAD

**Issue by fujiwarat** [mike-fabian/ibus-table#6]
Forwarding from https://github.com/ibus/ibus/issues/1992

Which distribution and version?:
Debian GNU/Linux 9 (stretch)

Which desktop environment and version?:
XFCE 4.12

Which session type?:
X11

IBus version?:
IBus 1.5.14

Issue description:

When I switch input mode between Chinese and English with Left Space, the icon in the tray does not change accordingly into English or Chinese, saying 五. I believe this is tiny bug for so beautiful ibus.

**Comment by mike-fabian** [comment]
I am not sure whether I understand that. Is the patch in the comment by Fujiwara San supposed to fix the problem? 

There seems to be no icon for English mode.

![wubi](https://user-images.githubusercontent.com/2330175/39507890-6412941e-4de0-11e8-811f-76b06505651f.png)

**Comment by mike-fabian** [comment]
As you can see in the screenshot, the indicator at the left side of the floating panel changes from 中 to 英 when switching between Chinese and English mode. As you say, the icon in the tray is always 五 though.
But I cannot find any other ibus input method which changes the icon in the tray depending on input mode. Is this possible at all? How?

**Comment by fujiwarat** [comment]
> There seems to be no icon for English mode.

Hmm.., the content of your image is not expected by me.
Did you focus on a new input context after you run ibus-daemon?

My patch means to let ibus-ui-gtk3 know 'InputMode' is the property to draw the ibus panel icon.
When ibus-table switches the input modes, ibus-table calls IBus.Engine.update_property() from ibus-table/engine/table.py:_init_or_update_property_menu() and ibus-table sends 'InputMode' property.
ibus-ui-gtk3 receives properties from ibus-table and if the property is 'InputMode', ibus-ui-gtk3 checks 'InputMode.symmbol' and draws the icon as a string.

The same implementation has been done in ibus-anthy and ibus-libpinyin (and ibus-kkc?).

**Comment by fujiwarat** [comment]
`ibus read-cache` should reflect the result to apply the 'icon_prop_key' patch.

**Comment by mike-fabian** [comment]
Oh, nice, I see that it works with ibus-anthy and ibus-libpinyin. It does *not* work with ibus-kkc.

**Comment by mike-fabian** [comment]
What could be the reason that it didn‘t work for me for ibus-table?
I applied the patch of course. And did "ibus read-cache" and rebooted.

**Comment by mike-fabian** [comment]
Oh, now I did 
rm .cache/ibus/bus/registry

and rebooted again, this made it work. Great!!

**Comment by mike-fabian** [comment]
Sorry for forgetting this, you wrote it above.

**Comment by mike-fabian** [comment]
Fixed in https://github.com/mike-fabian/ibus-table/releases/tag/1.9.20
