### ISSUE TITLE
Improve priorities in cangjie5 table

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-table#76]
https://github.com/kaio/ibus-table/issues/73#issuecomment-863162081

okr 知 1000
okr 佑 1000
xokr 佑 1000

irp 感 1000
irp 怠 1000
xirp 怠 1000

$ grep '^iod\|^xiod' cangjie5.txt 
iod	庥	1000
iod	楽	1000
iod	栥	1000
iodf	𢊒	1000
iodi	府	1000
xiod	楽	1000

Check if the priority of characters which have an additional way to type them, starting with x, should have lower priority or not.

Does their Big5 code already give them lower priority in all cases or not?

**Comment by WhiteCzar** [comment]
Hey! How's the progress on this thing going?
I just distro hopped to Fedora and now I am on the latest ibus-table package (though it required some jumping through hoops; it's impossible to install cangjie IME from the GUI Software center for some reason, you need to manually install it with dnf in the terminal)
Is there any way I can help in making this improved priorities in cangjie5 a reality?
Or at least have you decided on pursuing this path?

**Comment by mike-fabian** [comment]
Not yet, I’ll try to have a look between Christmas and New Year.

**Comment by WhiteCzar** [comment]
By the way (I know it's a separate issue but I'm not sure where I should open it or if I should at all).

Is it possible to be able to install ibus-table-chinese-cangjie via the graphical gnome software app?

Right now it only allows you to install ibus-table itself, but that doesn't install any actual IMEs. I consider that a UX bug.

**Comment by WhiteCzar** [comment]
By the way, getting back to the topic of this issue:

https://github.com/Jackchows/Cangjie5/releases/tag/v1.8.1
http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194346

There's a hack that lets Windows use Cangjie v.5 instead of the Cangjie v.3 that Windows only ships with, and the way the table is structured there is exactly the way I propose we restructure ibus-table-chinese-cangjie5.

You may take a look at that github page. Maybe it will be possible to just copy some code from there?

**Comment by WhiteCzar** [comment]
P.S.: You can read Trad Chinese, right? Those pages are only in Trad Chinese.

**Comment by mike-fabian** [comment]
> Hey! How's the progress on this thing going? I just distro hopped to Fedora 35 and now I am on the latest ibus-table package (though it required some jumping through hoops; it's impossible to install cangjie IME from the GUI Software center for some reason, you need to manually install it with dnf in the terminal)

I think this is a bug in the ibus-table-chinese.spec file. I opened this bug:

https://bugzilla.redhat.com/show_bug.cgi?id=2035337

**Comment by WhiteCzar** [comment]
Thanks!

**Comment by mike-fabian** [comment]
> > Hey! How's the progress on this thing going? I just distro hopped to Fedora 35 and now I am on the latest ibus-table package (though it required some jumping through hoops; it's impossible to install cangjie IME from the GUI Software center for some reason, you need to manually install it with dnf in the terminal)
> 
> I think this is a bug in the ibus-table-chinese.spec file. I opened this bug:
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=2035337

I think I fixed this, but it will take some time until the fix gets into stable into Fedora 35, see:

https://bodhi.fedoraproject.org/updates/FEDORA-2021-59763e096e

**Comment by mike-fabian** [comment]
> P.S.: You can read Trad Chinese, right? Those two webpages are only in Trad Chinese.

No, I cannot read Chinese.

**Comment by mike-fabian** [comment]
> Getting back to the topic of this issue:
> 
> https://github.com/Jackchows/Cangjie5/releases/tag/v1.8.1 http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194346
> 
> There's a hack that lets Windows use Cangjie v.5 instead of the Cangjie v.3 that Windows only ships with, and the way the table is structured there is exactly the way I propose we restructure ibus-table-chinese-cangjie5. (I.e., characters that have an additional way to type them, starting with x, have lower priority than those that don't.)
> 
> You may take a look at that github page. Maybe it will be possible to just copy some code from there?

Can you explain this in more detail? I don’t see any priorities in https://raw.githubusercontent.com/Jackchows/Cangjie5/master/Cangjie5_TC.txt

**Comment by WhiteCzar** [comment]
Hm... I'm very sorry, I just don't have any programming skills, so I can't really explain how exactly it is done.
So I can only explain the end result. In Jackchows' table, if I type `okr` it gives me 知 as the first choice and if I type `xokr` it gives me 佑, just as it's logically supposed to work. But in ibus-table-cangjie5 right now `okr` gives 佑 as the first choice, just the same as `xokr`, which is a bug, I'm quite sure (and Jackchows' treatment of those kinds of pairs make me even more sure of this). This is only just example, but there are many such examples. Right now ibus-table-cangjie5 treats most of the in the wrong way (though some are correct).

**Comment by WhiteCzar** [comment]
I could write an email in Chinese to the maintainer of Jackchows' table and ask him how he did this if you want. But maybe you need to give me some outline of what exactly I should ask him. I mean the more technical terms, I guess. In fact, he may actually speak English.

**Comment by WhiteCzar** [comment]
> which I'm quite sure is a bug

The reason for this bug in cangjie5 is also quite clear to me. It's because those orders (`okr` -> first 佑 second 知) were probably randomly assigned in cangjie3, where there is no way to distinguish between those two character using the `x`-prefix. Then nobody bothered to change the order in ibus-chinese-cangjie5.

**Comment by WhiteCzar** [comment]
> randomly assigned in cangjie3,

That is not to say that those orders should be changed in ibus-table-cangjie3. For cangjie3 these particular orders, though probably randomly assigned at first, have become a custom for cangjie3 users by now. I only propose to change those orders in cangjie5, where a better way of distinguishing between those pairs or characters exist by using the `x`-prefix.

**Comment by WhiteCzar** [comment]
> > Getting back to the topic of this issue:
> > https://github.com/Jackchows/Cangjie5/releases/tag/v1.8.1 http://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=194346
> > There's a hack that lets Windows use Cangjie v.5 instead of the Cangjie v.3 that Windows only ships with, and the way the table is structured there is exactly the way I propose we restructure ibus-table-chinese-cangjie5. (I.e., characters that have an additional way to type them, starting with x, have lower priority than those that don't.)
> > You may take a look at that github page. Maybe it will be possible to just copy some code from there?
> 
> Can you explain this in more detail? I don’t see any priorities in https://raw.githubusercontent.com/Jackchows/Cangjie5/master/Cangjie5_TC.txt

Actually, I just looked at that github page once again, and I think it's quite simple.

grep for:
知	okr
佑	okr
As you see, 知 comes on top. I think this is how he maintains the correct priorities. The character that should come first in IME comes first in the table.

**Comment by WhiteCzar** [comment]
感	irp
怠	irp

same for this pair
(note: in ibus-table-cangjie5 the priorities are reversed for both of these two pairs)

**Comment by mike-fabian** [comment]
> Hm... I'm very sorry, I just don't have any programming skills, so I can't really explain how exactly it is done. So I can only explain the end result. In Jackchows' table, if I type `okr` it gives me 知 as the first choice and if I type `xokr` it gives me 佑, just as it's logically supposed to work. But in ibus-table-cangjie5 right now `okr` gives 佑 as the first choice, just the same as `xokr`, which I'm quite sure is a bug (and Jackchows' treatment of those kinds of pairs make me even more sure of this). This is just one example, but there are many such examples. Right now ibus-table-cangjie5 treats most of such character pairs in the wrong way (though some are correct).

If it is only that,  I don’t need to look at that other project, if all I need to know is that the result of `x???` needs to have higher priority than the result of the same input without the `x`, than  I can do the work without looking at anthing else.

**Comment by mike-fabian** [comment]
Something different: Do you have any opinion on this?: https://github.com/mike-fabian/ibus-table/issues/85#issuecomment-1000423967

**Comment by mike-fabian** [comment]
> 感 irp 怠 irp
> 
> same for this pair (note: in ibus-table-cangjie5 the priorities are reversed for both of these two pairs)

```
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables/cangjie (master)
$ egrep '^x?okr\s' cangjie5.txt
okr	知	1000      Big5: AABE
okr	佑	1000      Big5: A6F6
xokr	佑	1000
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables/cangjie (master)
$ egrep '^x?irp\s' cangjie5.txt
irp	感	1000      Big5: B750
irp	怠	1000      Big5: ABE5
xirp	怠	1000
mfabian@taka:/local/mfabian/src/ibus-table-chinese/tables/cangjie (master)
$
```

(I added the Big5 codes manually to the grep output, for the Big5 codes see the `kBigFive` value in:

https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E7%9F%A5
https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E4%BD%91
https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E6%84%9F
https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E6%80%A0

)

Currently, for the tables 

```
'cangjie3', 'cangjie5', 'cangjie-big',
'quick-classic', 'quick3', 'quick5'
```

ibus-table uses the Big5 code as a tie breaker when all else is equal
(same input, same user frequency, same system frequency (always 1000 in cangjie5.txt), ...)

The idea was that the Big5 code points are at least roughly ordered by how frequent the characters are, so as a last ditch effort to achieve reasonable sorting if all else is equal for the above cangjie tables, the Big5 code is used.

We can achieve what we want if I change the cangjie5.txt file like this:

For all lines starting with `x` check whether there is another line containing the same Chinese character with the same input to type without the `x`. If such a line exist, change the priority from 1000 to 999.

**Comment by WhiteCzar** [comment]
> For all lines starting with `x` check whether there is another line containing the same Chinese character with the same input to type without the `x`. If such a line exists, change the priority from 1000 to 999.

Yes! That's pretty much exactly what should be done here in my opinion.



> The idea was that the Big5 code points are at least roughly ordered by how frequent the characters are, so as a last ditch effort to achieve reasonable sorting if all else is equal for the above cangjie tables, the Big5 code is used.

I'm not really sure about that. 知 means 'to know' and is an extremely common character; 佑 means 'protected [by a deity or a person]' and isn't as common. So, this doesn't seem like it was based on frequency at all.

**Comment by WhiteCzar** [comment]
> If such a line exists, change the priority from 1000 to 999.

You mean, change the priority to 999 in the input without x, right? In other words,
okr 知 1000
okr 佑 999

**Comment by mike-fabian** [comment]
> > If such a line exists, change the priority from 1000 to 999.
> 
> You mean, change the priority to 999 in the input without x, right? In other words, okr 知 1000 okr 佑 999

Yes, exactly.

**Comment by mike-fabian** [comment]
> > > If such a line exists, change the priority from 1000 to 999.
> > 
> > 
> > You mean, change the priority to 999 in the input without x, right? In other words, okr 知 1000 okr 佑 999
> 
> Yes, exactly.

I’ll start to work on this soon.

**Comment by mike-fabian** [comment]
Branch with the work I did so far:

https://github.com/mike-fabian/ibus-table-chinese/tree/ibus-table-issue-76

This branch adds two commits. The first is a script to do the change, it looks like this:

https://github.com/mike-fabian/ibus-table-chinese/commit/f94823062becf66283cee3878a2b804fb98bd3ab#diff-d98a034f5cb8a0e3f07d5d8b5dc3c43723ea8d8b95199e18a82c52e072eca4dd

The second is the generated change. It looks like this:

https://github.com/mike-fabian/ibus-table-chinese/commit/89fdad3de62943efb6b26c4ab7d8df3827c0e8a9#diff-d98a034f5cb8a0e3f07d5d8b5dc3c43723ea8d8b95199e18a82c52e072eca4dd

**Comment by mike-fabian** [comment]
Update for Fedora 35 containing the improved cangjie5 table:

https://bodhi.fedoraproject.org/updates/FEDORA-2021-8808d4f69f

**Comment by WhiteCzar** [comment]
Can I get this update through the GNOME Software update or dnf update?

**Comment by WhiteCzar** [comment]
Oh, I see

`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2021-8808d4f69f`

I will test this on Monday. I'm away from my main PC this weekend. Happy New Year!

**Comment by mike-fabian** [comment]
Yes, this command with `dnf` is the right way to get this update.

Happy new year!

**Comment by WhiteCzar** [comment]
Just tested it. Works perfectly. Thank you!

**Comment by mike-fabian** [comment]
Thank you for testing!
I made a pull request to get this improved cangjie5.txt included upstream:

https://github.com/definite/ibus-table-chinese/pull/19

**Comment by mike-fabian** [comment]
The pull request is merged upstream, I think I can close this.
