### ISSUE TITLE
Provide cmdline method to toggle 'input-mode'

### ISSUE THREAD

**Issue by mozbugbox** [mike-fabian/ibus-table#85]
Most of the settings of ibus table can be accessed from the  command line  through the `gsettings`. However, the `input mode` action was intentionally detached from the `gsettings`. Therefore there are no simple means to access the `input mode` from the cmdline.

I'd like to have ibus-table auto switch to the `direct input mode` (English mode) whenever getting out of the `insert mode` in `Vim`. And then switch back into whatever `input mode` it was when vim enters the `insert mode` again.

To make it work, a way to find out what current `input mode` is in from the cmdline, is also needed. 

Maybe a dbus API?

**Comment by mike-fabian** [comment]
Maybe just save it to gsettings like all the other settings, that would be easier.

At the moment we have a setting `inputmode` which is actually the default input mode when ibus-table starts.

But when the input mode is changed while ibus-table is running, this change is not save to  the `inputmode` setting.

How about just adding another setting `currentinputmode`?

When the input mode is changed while ibus-table is running by a key binding or the property meny, the value of this `currentinputmode` would change as well. And changing `currentinputmode` with `gsettings` from the commandline would also change the input mode of the currently running ibus-table.

When restarting, ibus-table would then read the default input mode  from the `inputmode` gsettings and write what is found there also to the `currentinputmode` gsetting.

**Comment by mike-fabian** [comment]
Even easier and maybe nicer would be to do it the way it is done in ibus-typing-booster (I prefer that behaviour):

- two gsettings variables `inputmode` and `rememberinputmode`
- `inputmode` is always saved to gsettings when changed with a keybinding or with the property menu. When changing it from the command line, it has an effect on the running ibus-table
- `rememberinputmode` can be changed in the setup tool with a checkbox setting, if it is checked the `inputmode` setting is used when ibus-table starts. I.e. after a restart, ibus-table starts with the `inputmode` which was used last in the previous session. If `rememberinputmode` is not checked, ibus-table defaults to Chinese mode (Table mode)  after a restart.

I like that behaviour better, but it is a change to the current behaviour which some users might have liked and are used to.

My idea from my previous comment, add a `currentinputmode` gsetting would only make it possible to change the current input mode by changing that gsetting from  the command line but otherwise it would not change the behaviour of ibus-table at all.

**Comment by mike-fabian** [comment]
Would it be OK for you if I implement it as in my last comment?

**Comment by WhiteCzar** [comment]
![Screenshot from 2021-12-30 10-00-15](https://user-images.githubusercontent.com/85533924/147715743-6ab7e0c9-1b4f-4760-a5af-36708ed8e30b.png)

Let me make sure I understand correctly. The way the setup menu works is that the first entry 'Input mode' is the default mode used after a restart, right?
You want to change that so `inputmode` would mean the current input mode, which will be forgotten after a restart. The default input mode then would be set to Table, without any way to change the default. But you could check the `rememberinput` box to remember the last input mode used before a restart, and continue using it after a restart. Correct?

**Comment by WhiteCzar** [comment]
I can see where a problem could arise with this method. In gnome one can set input source switching setting as such:
![image](https://user-images.githubusercontent.com/85533924/147716002-397ea954-1600-452f-8cfc-d8c4353a78fe.png)
This way one can have two windows open and two different keyboard layouts for those windows. However, ibus-table currently doesn't work well with this method (it's another issue, actually). If I open two windows and use Table in one of them, then switch to another, use Direct in there, then switch to the first window, the input method will just reset. Both windows will be Table again. It does not remember that the second window was Direct.

**Comment by WhiteCzar** [comment]
Right now, however, I can at least set the default ibus-table input mode, so every new window I open will have that method. But if you remove the option to set the default mode, this will completely break. Because ibus-table doesn't actually remember input methods between windows.

**Comment by WhiteCzar** [comment]
If you can somehow improve ibus-table to remember that one used Table in one window and Direct in another, then the changes you propose will not break anything.

**Comment by mozbugbox** [comment]
The 2nd method is fine. Since I have not really notice what input mode was when first starts ibus-table, I haven't think of what's the use of the 1st time input mode is for.

**Comment by mozbugbox** [comment]
> If you can somehow improve ibus-table to remember that Table is used in one window and Direct in another (when used with 'Switch input sources individually for each window'), then the changes you propose will not break anything.

Once this issue was `fixed`, I believe Gnome can implement the  'Switch input sources individually for each window' feature for ibus-table with remembered input mode.

**Comment by mozbugbox** [comment]
Actually, I'm not using gnome. I can have ibus use different input method for different application by settings through `ibus-setup`->preferences->advanced. The input mode for ibus-table was remembered too.

**Comment by WhiteCzar** [comment]
What DE are you using? I just tried doing what you did with ibus-setup, but it doesn't work. ![Screenshot from 2021-12-30 11-07-41](https://user-images.githubusercontent.com/85533924/147718532-e596285d-aa28-443b-bc04-63a6e7674ab0.png)
ibus-table still doesn't remember the input states among different windows.

**Comment by WhiteCzar** [comment]
Anyway, I don't have any objections to Mike's 2nd way. All the people I've seen using Chinese input use Chinese as default and not English (that is, Table, and not Direct, in the case of cangjie). I just outlined an issue it might worsen, but this issue exists already.

**Comment by mike-fabian** [comment]
> Anyway, I don't have any objections to Mike's 2nd way. All the people I've seen using Chinese input use Chinese as default and not English (that is, Table, and not Direct, in the case of cangjie). I just outlined an issue it might worsen, but this issue exists already.

The issue you mentioned is just a misunderstanding. “Switch input sources individually for each window” does not help in remembering any differences in settings of ibus-table between the different windows, as you correctly observed.

It is for remembering completely different input methods. For example, if you use ibus-table in window 1 but use just a US English keyboard layout in window 2, this will be remembered and if you switch to window 1, ibus-table will be active (with whatever the current settings of ibus-table are) and if you switch to window 2, the US keyboard layout will be active.

Ibus-table in direct input mode behaves very similar to an US keyboard layout, but this is **not** the same, it is still ibus-table.

This feature of ibus to remember different input methods for different windows is really only for different input methods, not for different settings of the same input methods. Different settings of the same input method cannot be remembered on a per window basis.

**Comment by mike-fabian** [comment]
> > If you can somehow improve ibus-table to remember that Table is used in one window and Direct in another (when used with 'Switch input sources individually for each window'), then the changes you propose will not break anything.
> 
> Once this issue was `fixed`, I believe Gnome can implement the 'Switch input sources individually for each window' feature for ibus-table with remembered input mode.

I think what you are using and what  @WhiteCzar actually wants is ibus-table in one window and an US English keyboard layout in the other window.

That works fine. 

But one cannot have ibus-table in Table mode and ibus-table in Direct mode in different windows. The settings of any input method like ibus-table are always global for the whole desktop.

**Comment by mike-fabian** [comment]
> The 2nd method is fine. Since I have not really notice what input mode was when first starts ibus-table, I haven't think of what's the use of the 1st time input mode is for.

Great, thank you! Then I’ll implement it like this!

**Comment by mozbugbox** [comment]
While the current behavior of the `input mode` amount the different windows under the NOT share input method b/w app mode is confusing(?).

When both windows are in ibus-table:
* win-1 in `table mode`
* tab to win-2, win-2 in `table mode`
* switch to `direct mode` in win-2
* tab to win-1, ibus-table jumps back to `table mode` in win-1
* tab to win-2, ibus-table stays at `table mode`

after some more switching, I'm stuck in the `direct mode`, i.e. Whatever the mode of the other window is, when I turn on the `table mode` in the current window, then switch to the other window and back, ibus-table is always in the `direct mode`.

**Comment by WhiteCzar** [comment]
> > > If you can somehow improve ibus-table to remember that Table is used in one window and Direct in another (when used with 'Switch input sources individually for each window'), then the changes you propose will not break anything.
> > 
> > 
> > Once this issue was `fixed`, I believe Gnome can implement the 'Switch input sources individually for each window' feature for ibus-table with remembered input mode.
> 
> I think what you are using and what @WhiteCzar actually wants is ibus-table in one window and an US English keyboard layout in the other window.
> 
> That works fine.
> 
> But one cannot have ibus-table in Table mode and ibus-table in Direct mode in different windows. The settings of any input method like ibus-table are always global for the whole desktop.

Well, in any case, it'd be nice to test your build with these new features! Sounds interesting, and hopefully that won't introduce any new issues.

**Comment by mike-fabian** [comment]
> While the current behavior of the `input mode` amount the different windows under the NOT share input method b/w app mode is confusing(?).
> 
> When both windows are in ibus-table:
> 
>     * win-1 in `table mode`
> 
>     * tab to win-2, win-2 in `table mode`
> 
>     * switch to `direct mode` in win-2
> 
>     * tab to win-1, ibus-table jumps back to `table mode` in win-1
> 
>     * tab to win-2, ibus-table stays at `table mode`
> 
> 
> after some more switching, I'm stuck in the `direct mode`, i.e. Whatever the mode of the other window is, when I turn on the `table mode` in the current window, then switch to the other window and back, ibus-table is always in the `direct mode`.

I cannot reproduce that. Does that happen only with specific windows? Maybe with windows using different toolkits? I tried with gedit and xterm but could not reproduce it for these two windows either.

**Comment by mozbugbox** [comment]
I tested the ibus-table using lxterminal (the term of LXDE) and roxterm. I believe both of the terminal were based on GTK-3.

**Comment by mike-fabian** [comment]
I  cannot reproduce this with lxterminal and roxterm either.

**Comment by mike-fabian** [comment]
> Even easier and maybe nicer would be to do it the way it is done in ibus-typing-booster (I prefer that behaviour):
> 
>     * two gsettings variables `inputmode` and `rememberinputmode`
> 
>     * `inputmode` is always saved to gsettings when changed with a keybinding or with the property menu. When changing it from the command line, it has an effect on the running ibus-table
> 
>     * `rememberinputmode` can be changed in the setup tool with a checkbox setting, if it is checked the `inputmode` setting is used when ibus-table starts. I.e. after a restart, ibus-table starts with the `inputmode` which was used last in the previous session. If `rememberinputmode` is not checked, ibus-table defaults to Chinese mode (Table mode)  after a restart.
> 
> 
> I like that behaviour better, but it is a change to the current behaviour which some users might have liked and are used to.
> 
> My idea from my previous comment, add a `currentinputmode` gsetting would only make it possible to change the current input mode by changing that gsetting from the command line but otherwise it would not change the behaviour of ibus-table at all.

I have implemented this now.

ibus-table-1.15.1 packages with that new feature for Fedora are here:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/builds/

As this is a (small) change in behaviour and not just a bugfix, I think I’ll release this as 1.16.0 after some testing.

**Comment by igor-kobzev** [comment]
> Even easier and maybe nicer would be to do it the way it is done in ibus-typing-booster (I prefer that behaviour):
> 
>     * two gsettings variables `inputmode` and `rememberinputmode`
> 
>     * `inputmode` is always saved to gsettings when changed with a keybinding or with the property menu. When changing it from the command line, it has an effect on the running ibus-table
> 
>     * `rememberinputmode` can be changed in the setup tool with a checkbox setting, if it is checked the `inputmode` setting is used when ibus-table starts. I.e. after a restart, ibus-table starts with the `inputmode` which was used last in the previous session. If `rememberinputmode` is not checked, ibus-table defaults to Chinese mode (Table mode)  after a restart.
> 
> 
> I like that behaviour better, but it is a change to the current behaviour which some users might have liked and are used to.
> 
> My idea from my previous comment, add a `currentinputmode` gsetting would only make it possible to change the current input mode by changing that gsetting from the command line but otherwise it would not change the behaviour of ibus-table at all.

Do I understand correctly that you implemented the way it is done in ibus-typing-booster?

**Comment by igor-kobzev** [comment]
First quick comment, before I get into more serious testing, why did you delete the toggle between a table and a direct input from the setup menu? I don't have a strong preference either way, but I'm just curious.

**Comment by igor-kobzev** [comment]
First comment on the new functionality: I like it very much that the input mode doesn't get reset if switched between different windows, if 'Choose individual input source for each window' is toggled on in Gnome Settings. In a sense, this fixed the issue I was talking about in this comment:


> I can see where a problem could arise with this method. In gnome one can set input source switching setting as such:
> ![image](https://user-images.githubusercontent.com/85533924/147716002-397ea954-1600-452f-8cfc-d8c4353a78fe.png)
> This way one can have two windows open and two different keyboard layouts for those windows. However, ibus-table currently doesn't work well with this method (it's another issue, actually). If I open two windows and use Table in one of them, then switch to another, use Direct in there, then switch to the first window, the input method will just reset. Both windows will be Table again. It does not remember that the second window was Direct.

That's nice!

**Comment by igor-kobzev** [comment]
By the way, I suggest the 'Remember input mode' toggle be turned on by default, otherwise people might not even realize it's there. It seems quite convenient.

**Comment by igor-kobzev** [comment]
Okay. Remembering states seem to work really well after a reboot as well. I am very happy with the way this toggle-on works now together with the 'Switch input sources individually for each window'. Didn't even expect it would solve that problem.

So I think @mozbugbox should test it if this solves his terminal problem. I am quite happy with this update.

**Comment by mike-fabian** [comment]
> First quick comment, before I get into more serious testing, why did you delete the toggle between a table and a direct input from the setup menu? I don't have a strong preference either way, but I'm just curious.

The old toggle for table and direct input mode was to specify the mode ibus-table started in. I.e. when this was set to "table mode", ibus-table always started in “table mode” (Chinese mode in case of Cangjie). If this toogle was set to “Direct input”, ibus-table did start in “Direct Input” (aka English mode). 

This has been replaced now with a toggle to choose whether the current mode should be remembered for the next restart or not.

For example, if this is set to “yes” and you are in “table mode” and restart your session, the new session will start in “table mode”. And if you are in “direct mode” and restart your session, the new session will start in “direct mode”.

If this toggle is set to “No”, then every new session will always start in “Table mode” (aka Chinese mode).

**Comment by mike-fabian** [comment]
> Also, does the 'Remember input mode' toggle on also saves such settings as 'Table input letter width' etc? Or these are always saved without any regard to that toggle and that toggle only has effect on the Table/Direct input?

All the other settings are always remembered anyway (that didn’t change), the new toggle only has an effect on Table/Direct mode.

**Comment by mike-fabian** [comment]
> First comment on the new functionality: I like it very much that the input mode doesn't get reset if switched between different windows, if 'Choose individual input source for each window' is toggled on in Gnome Settings. In a sense, this fixed the issue I was talking about in this comment:
> 
> > I can see where a problem could arise with this method. In gnome one can set input source switching setting as such:
> > ![image](https://user-images.githubusercontent.com/85533924/147716002-397ea954-1600-452f-8cfc-d8c4353a78fe.png)
> > This way one can have two windows open and two different keyboard layouts for those windows. However, ibus-table currently doesn't work well with this method (it's another issue, actually). If I open two windows and use Table in one of them, then switch to another, use Direct in there, then switch to the first window, the input method will just reset. Both windows will be Table again. It does not remember that the second window was Direct.
> 
> That's nice!

I am surprised that it has any effect on this. I could not reproduce this problem, even with the previous version  of ibus-table.

**Comment by mike-fabian** [comment]
> Do I understand correctly that you implemented it the way it is done in ibus-typing-booster?

Yes.

**Comment by igor-kobzev** [comment]
> > First quick comment, before I get into more serious testing, why did you delete the toggle between a table and a direct input from the setup menu? I don't have a strong preference either way, but I'm just curious.
> 
> The old toggle for table and direct input mode was to specify the mode ibus-table started in. I.e. when this was set to "table mode", ibus-table always started in “table mode” (Chinese mode in case of Cangjie). If this toogle was set to “Direct input”, ibus-table did start in “Direct Input” (aka English mode).
> 
> This has been replaced now with a toggle to choose whether the current mode should be remembered for the next restart or not.
> 
> For example, if this is set to “yes” and you are in “table mode” and restart your session, the new session will start in “table mode”. And if you are in “direct mode” and restart your session, the new session will start in “direct mode”.
> 
> If this toggle is set to “No”, then every new session will always start in “Table mode” (aka Chinese mode).

Gotcha!

**Comment by mike-fabian** [comment]
> By the way, I suggest the 'Remember input mode' toggle be turned on by default, otherwise people might not even realize it's there. It seems quite convenient.

I may do that later, I am thinking about that ...

**Comment by igor-kobzev** [comment]
> > First comment on the new functionality: I like it very much that the input mode doesn't get reset if switched between different windows, if 'Choose individual input source for each window' is toggled on in Gnome Settings. In a sense, this fixed the issue I was talking about in this comment:
> > > I can see where a problem could arise with this method. In gnome one can set input source switching setting as such:
> > > ![image](https://user-images.githubusercontent.com/85533924/147716002-397ea954-1600-452f-8cfc-d8c4353a78fe.png)
> > > This way one can have two windows open and two different keyboard layouts for those windows. However, ibus-table currently doesn't work well with this method (it's another issue, actually). If I open two windows and use Table in one of them, then switch to another, use Direct in there, then switch to the first window, the input method will just reset. Both windows will be Table again. It does not remember that the second window was Direct.
> > 
> > 
> > That's nice!
> 
> I am surprised that it has any effect on this. I could not reproduce this problem, even with the previous version of ibus-table.

How to reproduce this problem with previous versions:

1. You need to have several input methods. E.g., Cangjie, English, German, French, Russian etc.
2. Your default (startup) input method should not be Cangjie.
3. Toggle 'Switch input sources individually for each window' on
4. Open two windows and navigate to Cangjie on each of them
5. In one of those windows, switch from Table to Direct mode
6. Switch to another window
Result: It's back to Table again
7. Switch back to the first window
Result: It's back to Table as well (although the icon on the top bar suggests it's in Direct mode!

Now this is not a problem anymore, as Table/Direct is saved across windows even if 'Switch sources individually for each window' is enabled.

**Comment by mike-fabian** [comment]
> Okay. Remembering states seems to work as expected after a reboot as well. I am very happy with the way this toggle-on works now together with the 'Switch input sources individually for each window'. Didn't even expect it would solve that problem.
> 
> So I think @mozbugbox should test whether this update solves his terminal problem. I am quite happy with it.

Great!

The problem @mozbugbox reported is solved, I think.

Now it is possible to check whether one is in “Table mode” or “Direct mode” from the command line like this:

```
$ dconf read /org/freedesktop/ibus/engine/table/cangjie5/inputmode
1
```

Here a `1` is returned which means it is in “Table mode”.

And one can switch to “Direct mode” like this:

```
$ dconf write /org/freedesktop/ibus/engine/table/cangjie5/inputmode 0
```

And back to “Table mode” like this:

```
$ dconf write /org/freedesktop/ibus/engine/table/cangjie5/inputmode 1
```

**Comment by mike-fabian** [comment]
> > > First comment on the new functionality: I like it very much that the input mode doesn't get reset if switched between different windows, if 'Choose individual input source for each window' is toggled on in Gnome Settings. In a sense, this fixed the issue I was talking about in this comment:
> > > > I can see where a problem could arise with this method. In gnome one can set input source switching setting as such:
> > > > ![image](https://user-images.githubusercontent.com/85533924/147716002-397ea954-1600-452f-8cfc-d8c4353a78fe.png)
> > > > This way one can have two windows open and two different keyboard layouts for those windows. However, ibus-table currently doesn't work well with this method (it's another issue, actually). If I open two windows and use Table in one of them, then switch to another, use Direct in there, then switch to the first window, the input method will just reset. Both windows will be Table again. It does not remember that the second window was Direct.
> > > 
> > > 
> > > That's nice!
> > 
> > 
> > I am surprised that it has any effect on this. I could not reproduce this problem, even with the previous version of ibus-table.
> 
> How to reproduce this problem with previous versions:
> 
>     1. You need to have several input methods. E.g., Cangjie, English, German, French, Russian etc.
> 
>     2. Your default (startup) input method should not be Cangjie.
> 
>     3. Toggle 'Switch input sources individually for each window' on
> 
>     4. Open two windows and navigate to Cangjie on each of them
> 
>     5. In one of those windows, switch from Table to Direct mode
> 
>     6. Switch to another window
>        Result: It's back to Table again
> 
>     7. Switch back to the first window
>        Result: It's back to Table as well (although the icon on the top bar suggests it's in Direct mode!)
> 
> 
> Now this is not a problem anymore, as Table/Direct is saved across windows even if 'Switch sources individually for each window' is enabled.

You are right, I tested again with ibus-table-1.15.0 and then with ibus-table-1.15.1 in Gnome Xorg and the update does indeed fix that problem. But **only** **if** `Remember input mode` is set to `Yes`.

That is a strong argument to make `Yes` the default, I think.

Personally, I strongly prefer the `Yes` setting anyway. And if it also solves that problem with the different windows, then I should really make it the default.

**Comment by igor-kobzev** [comment]
> That is a strong argument to make `Yes` the default, I think.

Exactly! And I don't think anyone would mind. It's very easy to switch to the original option if someone doesn't like it. I think most people wouldn't even notice the difference except for those who would be grateful for it.
