### ISSUE TITLE
Improve priorities in cangjie5 table v.2

### ISSUE THREAD

**Issue by igor-kobzev** [mike-fabian/ibus-table#87]
This is an issue to fix some leftover characters that weren't solved by issue #76.

I just ran into a pair of characters that were not fixed:

`afmbc` gives 顯 and 顥, with 顥 on top
`xafmb[c]` gives 顥

The reason why this happened, I assume, is because the second character code: `xafmbc` should be a six-character-string code, but that would overflow the five-character-string buffer in cangjie. As a result, to get that character you need to type `xafmb` instead of `xafmbc`, and because of that, your script missed this pair (and possibly other such pairs, although I am not sure how many there are).

Solution: perhaps write another script that would check for codes starting with `x-` that don't have a corresponding `x-`less code (for instance, there is `xafmb` (顥), but there is no `afmb`). There could be very few of those, so after that it may be possible to pick the ones to change the priorities of manually. Otherwise, might be necessary to think of some other logic to deduce which ones should be changed and in what way.

**Comment by mike-fabian** [comment]
```
$ egrep '^x?afmb' cangjie5.txt
afmbc   顯      1000
afmbc   顥      1000
afmbc   𩓺      1000
afmbo   颢      1000
xafmb   顥      1000
```

**Comment by mike-fabian** [comment]
> The reason why this happened, I assume, is because the second character code: `xafmbc` should be a six-character-string code, but that would overflow the five-character-string buffer in cangjie.

```
$ grep MAX cangjie5.txt 
MAX_KEY_LENGTH = 5
```

We could change this to 6. I have no opinion at the moment whether that is a good idea or not.

If 6 character codes are not used in other implementations of cangjie, we should probably not use it either.

So before changing this to 6, I would like to know what other implementations of
cangjie5 (for example on Windows, MacOs, ...) do with

```
xafmb[c] gives 顥
```

Do they use `xafmb` or `xafmbc`?

**Comment by igor-kobzev** [comment]
Yeah, I also thought about that. Apparently it's 5 character-limit everywhere. That's something that that original author of cangjie, Chu Bong-Foo established. E.g., as you can see here: https://raw.githubusercontent.com/Jackchows/Cangjie5/master/Cangjie5_TC.txt, it also uses `xafmb` for that character. I don't know how it's implemented in Mac.
As a use of cangjie, I personally think that changing that to six-characters would be fine. But perhaps we're not ones to make this decision, since it's established that cangjie only uses fire-character codes. Maybe it's an issue that should be (and maybe has been) brought before the people who actually define the cangjie5 standards?

**Comment by mike-fabian** [comment]
> ```
> $ egrep '^x?afmb' cangjie5.txt
> afmbc   顯      1000
> afmbc   顥      1000
> afmbc   𩓺      1000
> afmbo   颢      1000
> xafmb   顥      1000
> ```

I also wonder what to do with `afmbc   𩓺      1000`.

By improving my script to change cangjie5.txt, I can find cases like

```
afmbc   顥      1000
xafmb   顥      1000
```

And then the result of improving the table with the improved script would be

```
afmbc   顯      1000
afmbc   顥      900
afmbc   𩓺      1000
afmbo   颢      1000
xafmb   顥      1000
```

The 3rd character, i.e.

```
afmbc   𩓺      1000
```

would still have priority 1000.

I noticed this already when I improved the table with the current script that there are some cases for a code starting with `x` that there are more then 2 characters with the same code without the `x` and my script changed only the priority of the one which also had the longer code starting with `x`. So the remaining 2 (sometimes there were even more) still have their order determined by their Big5 code.

**Comment by igor-kobzev** [comment]
> I noticed this already when I improved the table with the current script that there are some cases for a code starting with `x` that there are more then 2 characters with the same code without the `x` and my script changed only the priority of the one which also had the longer code starting with `x`. So the remaining 2 (sometimes there were even more) still have their order determined by their Big5 code.

Hm. I wonder how that would translate into real-word usage. Because so far I haven't noticed any issues. Those characters never pop up on top anyway.

**Comment by mike-fabian** [comment]
> > I noticed this already when I improved the table with the current script that there are some cases for a code starting with `x` that there are more then 2 characters with the same code without the `x` and my script changed only the priority of the one which also had the longer code starting with `x`. So the remaining 2 (sometimes there were even more) still have their order determined by their Big5 code.
> 
> Hm. I wonder how that would translate into real-word usage. Because so far I haven't noticed any issues with that. Those characters never pop up on top anyway.

If they never pop up on top, that would mean they all have higher Big5 codes than the other characters with the same cangjie5 code.

**Comment by igor-kobzev** [comment]
> If you ever find any such isssue, tell me, then we can fix the priorities in the table.

Okay!

**Comment by mike-fabian** [comment]
> There could be very few of those, so after that it may be possible to pick the ones to change the priorities of manually. Otherwise, might be necessary to think of some other logic to deduce which ones should be changed and in what way.

There are 268 of these.

**Comment by mike-fabian** [comment]
You can review lines to be changed in priority by clicking  on the above commit.

Does that look OK to you?

**Comment by igor-kobzev** [comment]
Oh gosh, that's a lot. I did not look at each one of the changes, but I randomly looked at a few, and they all seem okay. So I assume all the changes are probably fine.

**Comment by mike-fabian** [comment]
By the way, is this spelling correction OK?: 
https://github.com/definite/ibus-table-chinese/pull/17/commits/06f7482d367ff7180ad928f1c10235103476f8b8

**Comment by igor-kobzev** [comment]
> By the way, is this spelling correction OK?: [definite/ibus-table-chinese@06f7482](https://github.com/definite/ibus-table-chinese/commit/06f7482d367ff7180ad928f1c10235103476f8b8)

I commented on that commit.

**Comment by mike-fabian** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-76daebdbee
