### ISSUE TITLE
Check if Traditional/Simplified errors were introduced by the update of Unihan_Variants.txt to “2021-12-01 Unicode 15.0.0 draft”

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-table#97]
https://github.com/mike-fabian/ibus-table/commit/c1c39a3dd8aca8c334c00118ba54dd74995fbd47

Regenerate engine/chinese_variants.py for Unihan_Variants.txt from “2021-12-01 Unicode 15.0.0 draft”

    Because of the new Unihan_Variants.txt, the following 37 characters
    are added to the VARIANTS_TABLE in chinese_variants.py:
    u'䓨': 1, u'沄': 1, u'潕': 2, u'澐': 2, u'罃': 2, u'鮗': 2, u'龻': 2,
    u'鿟': 1, u'鿠': 2, u'鿰': 1, u'鿲': 1, u'鿳': 2, u'鿴': 1, u'鿵': 1,
    u'鿶': 1, u'鿷': 1, u'鿸': 1, u'鿹': 1, u'鿺': 1, u'𣲘': 1, u'𤇾': 2,
    u'𤪤': 2, u'𦥯': 2, u'𧰎': 2, u'𩷓': 2, u'𩷕': 2, u'𩹎': 2, u'𪄳': 2,
    u'𪛞': 1, u'𫇦': 1, u'𬉧': 2, u'𬵨': 2, u'𰀡': 1, u'𰀢': 1, u'𰁜': 1,
    u'𰃮': 1, u'𰯲': 2,

    1 = simplified Chinese
    2 = traditional Chinese
    3 = used both in simplified and traditional Chinese

**Comment by igor-kobzev** [comment]
So I wanted to ask. Who does those Unihan updates? Whoever it is, he seems highly unqualified. Nobody in their right mind knowing Japanese/Chinese would put 冬 in Simplified characters.
https://en.wiktionary.org/wiki/%E5%86%AC
I mean, you go to Wiktionary and you see that this is the character from the Warring States period. It is used in Taiwan, in Japan, and in China.

**Comment by igor-kobzev** [comment]
I'm not trying to diss anyone here! I'm just bringing this to your attention. If something like a new Unihan update can break Cangjie table, then maybe we should consider not linking it directly? So any bugs can be worked out before they influence Cangjie and other table inputs.
Cuz the thing with the 冬 character... it's just way too crazy. I cannot think of any rational reason it would be put in Simplified-only category.

**Comment by igor-kobzev** [comment]
Oops, I left the above two comments on the wrong issue, it seems. So I deleted them.

**Comment by igor-kobzev** [comment]
The rest seem correct to me. However, there are a few characters that don't display for me.
Do I need to download some fonts for them to display? I mean I have all the hanazono fonts for displaying the CJK Extentions fonts as per this page: https://ctext.org/font-test-page

**Comment by igor-kobzev** [comment]
> u'鿰': 1, u'鿲': 1, u'鿳': 2, u'鿴': 1, u'鿵': 1,
> u'鿶': 1, u'鿷': 1, u'鿸': 1, u'鿹': 1, u'鿺': 1,
> u'𪛞': 1, u'𰀡': 1, u'𰀢': 1, u'𰁜': 1,
> u'𰃮': 1, u'𰯲': 2,

These are the characters that aren't displayed (i.e., I get "tofu").

**Comment by mike-fabian** [comment]
> > u'鿰': 1, u'鿲': 1, u'鿳': 2, u'鿴': 1, u'鿵': 1,
> > u'鿶': 1, u'鿷': 1, u'鿸': 1, u'鿹': 1, u'鿺': 1,
> > u'𪛞': 1, u'𰀡': 1, u'𰀢': 1, u'𰁜': 1,
> > u'𰃮': 1, u'𰯲': 2,
> 
> These are the characters that aren't displayed (i.e., I get "tofu").

None of these display for me either at the moment. I have not investigated yet why, maybe they are new.

**Comment by mike-fabian** [comment]
> > > u'鿰': 1, u'鿲': 1, u'鿳': 2, u'鿴': 1, u'鿵': 1,
> > > u'鿶': 1, u'鿷': 1, u'鿸': 1, u'鿹': 1, u'鿺': 1,
> > > u'𪛞': 1, u'𰀡': 1, u'𰀢': 1, u'𰁜': 1,
> > > u'𰃮': 1, u'𰯲': 2,
> > 
> > 
> > These are the characters that aren't displayed (i.e., I get "tofu").
> 
> None of these display for me either at the moment. I have not investigated yet why, maybe they are new.

Many of those which display as Tofu are apparently not new, for example

'鿰' U+9FF0

https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E9%BF%B0

says:

“The Unicode Standard (Version 3.2)”

i.e. it is there for a long time already.

The only source given at https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E9%BF%B0

is

kIRG_GSource 	GKJ-00201

which according to

https://www.unicode.org/reports/tr38/index.html#kIRG_GSource

is “GKJ Terms in Sciences and Technologies (科技用字) approved by the China National Committee for Terms in Sciences and Technologies (CNCTST)”

But if none of our fonts have glyphs for that, I guess it is something really obscure, maybe nobody really uses that.

**Comment by mike-fabian** [comment]
> > u'沄': 1
> 
> This one is used in Trad:
> 
> https://dict.revised.moe.edu.tw/search.jsp?md=1&word=%E6%B2%84&qMd=0&qCol=1

I think I’ll fix only that one and assume that the classification of all the other characters is correct.

**Comment by igor-kobzev** [comment]
Sounds reasonable.

**Comment by igor-kobzev** [comment]
Here's another Trad/Simp character that's only marked as Simp:

干

**Comment by mike-fabian** [comment]
> Here's another Trad/Simp character that's only marked as Simp:
> 
> 干

Thank you, great!

**Comment by mike-fabian** [comment]
I made a new issue with a list of all characters in the cangjie5 table which are currently classified as simplified only.
Most of these are classified correctly, but there seem to be a few errors:

https://github.com/mike-fabian/ibus-table/issues/100

**Comment by mike-fabian** [comment]
Included in: https://github.com/mike-fabian/ibus-table/releases/tag/1.16.4

**Comment by mike-fabian** [comment]
Builds for Fedora are here: https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/

```
sudo dnf copr enable mfabian/ibus-table
sudo dnf update ibus-table
```
